'use strict';
const axios = require('axios');

const SCAN_EXTS = new Set([
  'js','ts','jsx','tsx','py','java','go','rb','php','cs','cpp','c','h',
  'yml','yaml','env','json','config','toml','sh','bash','tf','vue','svelte'
]);
const SKIP_DIRS = new Set([
  'node_modules','.git','dist','build','vendor','venv','.venv','env',
  '__pycache__','coverage','.next','.nuxt','out','target','bin','obj'
]);

function headers(token) {
  const h = { Accept: 'application/vnd.github.v3+json' };
  if (token) h['Authorization'] = 'token ' + token;
  return h;
}

function parseUrl(url) {
  const m = url.trim().replace(/\.git$/, '').match(/github\.com\/([^/]+)\/([^/\s]+)/);
  if (!m) throw new Error('Invalid GitHub URL. Use: https://github.com/owner/repo');
  return { owner: m[1], repo: m[2] };
}

async function getMeta(owner, repo, token) {
  try {
    const { data } = await axios.get(
      'https://api.github.com/repos/' + owner + '/' + repo,
      { headers: headers(token), timeout: 10000 }
    );
    return data;
  } catch (err) {
    if (err.response?.status === 404) throw new Error('Repository not found or is private. Add a GitHub token for private repos.');
    if (err.response?.status === 403) throw new Error('GitHub rate limit exceeded. Set GITHUB_TOKEN in .env to increase limits.');
    throw new Error('Could not fetch repository: ' + (err.message || 'Unknown error'));
  }
}

async function getFiles(owner, repo, token, path, depth) {
  if (depth > 4) return [];
  const files = [];
  try {
    const { data } = await axios.get(
      'https://api.github.com/repos/' + owner + '/' + repo + '/contents/' + (path || ''),
      { headers: headers(token), timeout: 12000 }
    );
    if (!Array.isArray(data)) return files;

    await Promise.allSettled(data.map(async item => {
      if (item.type === 'file') {
        const ext = item.name.split('.').pop()?.toLowerCase() || '';
        if (SCAN_EXTS.has(ext) && item.size > 0 && item.size < 200000) {
          files.push({ path: item.path, url: item.download_url, size: item.size });
        }
      } else if (item.type === 'dir' && !SKIP_DIRS.has(item.name)) {
        const sub = await getFiles(owner, repo, token, item.path, depth + 1);
        files.push(...sub);
      }
    }));
  } catch (_) {}
  return files;
}

async function fetchContent(url, token) {
  try {
    const { data } = await axios.get(url, {
      headers: token ? { Authorization: 'token ' + token } : {},
      timeout: 8000,
      responseType: 'text'
    });
    return typeof data === 'string' ? data : JSON.stringify(data);
  } catch (_) { return ''; }
}

async function createPR({ owner, repo, token, filePath, fixedContent, finding }) {
  const h = { ...headers(token), 'Content-Type': 'application/json' };
  const base = 'https://api.github.com/repos/' + owner + '/' + repo;

  const { data: repoData } = await axios.get(base, { headers: h });
  const defaultBranch = repoData.default_branch || 'main';

  const { data: refData } = await axios.get(base + '/git/refs/heads/' + defaultBranch, { headers: h });
  const baseSha = refData.object.sha;

  const { data: fileData } = await axios.get(base + '/contents/' + filePath, { headers: h });
  const fileSha = fileData.sha;

  const branch = 'codefortress/fix-' + finding.name.toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 30) + '-' + Date.now();
  await axios.post(base + '/git/refs', { ref: 'refs/heads/' + branch, sha: baseSha }, { headers: h });

  const encoded = Buffer.from(fixedContent).toString('base64');
  await axios.put(base + '/contents/' + filePath, {
    message: 'fix(security): patch ' + finding.name + ' [CodeFortress CI]',
    content: encoded, sha: fileSha, branch
  }, { headers: h });

  const { data: pr } = await axios.post(base + '/pulls', {
    title: '[CodeFortress CI] Fix ' + finding.name + ' in ' + filePath,
    body: '## Security Fix by CodeFortress CI\n\n**Vulnerability:** ' + finding.name + '\n**Severity:** ' + finding.severity + '\n**CWE:** ' + (finding.cwe || 'N/A') + '\n**File:** `' + filePath + '`\n**Line:** ' + (finding.line || 'N/A') + '\n\n### Vulnerable Code\n```\n' + (finding.lineText || 'N/A') + '\n```\n\n### Fix\n' + (finding.remediation || '') + '\n\n---\n*Auto-generated by CodeFortress CI*',
    head: branch, base: defaultBranch
  }, { headers: h });

  return { prUrl: pr.html_url, prNumber: pr.number, branch };
}

module.exports = { parseUrl, getMeta, getFiles, fetchContent, createPR };
